import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { getApiErrorMessage } from '../api/client';
import { createRateCard, listRateCards, updateRateCard, type CreateRateCardInput, type RateCard } from '../api/rateCards.api';
import { listZones, type Zone } from '../api/zones.api';

const initial: CreateRateCardInput = { orderType: 'B2C', fromZoneId: '', toZoneId: '', rateType: 'intra_zone', basePrice: 0, pricePerKg: 0, codSurchargeFlat: 0, codSurchargePct: 0 };

export default function AdminRateCardsPage() {
  const [cards, setCards] = useState<RateCard[]>([]); const [zones, setZones] = useState<Zone[]>([]); const [form, setForm] = useState(initial); const [editing, setEditing] = useState<RateCard | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [nextCards, nextZones] = await Promise.all([listRateCards(), listZones()]); setCards(nextCards); setZones(nextZones); setForm((current) => ({ ...current, fromZoneId: current.fromZoneId || nextZones[0]?.id || '', toZoneId: current.toZoneId || nextZones[0]?.id || '' })); } catch (caught) { setError(getApiErrorMessage(caught)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const updateForm = <K extends keyof CreateRateCardInput>(field: K, value: CreateRateCardInput[K]) => setForm((current) => ({ ...current, [field]: value }));
  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { const input = { ...form, rateType: form.fromZoneId === form.toZoneId ? 'intra_zone' as const : 'inter_zone' as const }; await createRateCard(input); setMessage('Rate card created.'); setForm((current) => ({ ...initial, fromZoneId: current.fromZoneId, toZoneId: current.toZoneId })); await load(); } catch (caught) { setError(getApiErrorMessage(caught)); } finally { setBusy(false); } }
  async function saveEdit(event: FormEvent) { event.preventDefault(); if (!editing) return; setBusy(true); setError(''); setMessage(''); try { await updateRateCard(editing.id, { basePrice: editing.basePrice, pricePerKg: editing.pricePerKg, codSurchargeFlat: editing.codSurchargeFlat, codSurchargePct: editing.codSurchargePct, isActive: editing.isActive }); setMessage('Rate card updated.'); setEditing(null); await load(); } catch (caught) { setError(getApiErrorMessage(caught)); } finally { setBusy(false); } }
  const moneyInput = (label: string, field: 'basePrice' | 'pricePerKg' | 'codSurchargeFlat' | 'codSurchargePct') => <label><span className="input-label">{label}</span><input className="input" type="number" min="0" step="0.01" value={form[field]} onChange={(e) => updateForm(field, Number(e.target.value))} required /></label>;
  return <div className="page-shell"><div><p className="eyebrow">Pricing configuration</p><h1 className="mt-3 font-display text-4xl font-bold">Rate cards</h1><p className="mt-3 max-w-2xl text-slate-600">Each order type and directional zone pair has one rate card. Quote calculations use active cards only.</p></div>
    {(error || message) && <p className={`mt-5 rounded-xl p-4 text-sm font-medium ${error ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700'}`}>{error || message}</p>}
    <form className="panel mt-8" onSubmit={create}><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Create</p><h2 className="mt-2 font-display text-2xl font-bold">New rate card</h2></div><span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-bold text-brand-700">{form.fromZoneId === form.toZoneId ? 'Intra-zone' : 'Inter-zone'}</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label><span className="input-label">Order type</span><select className="input" value={form.orderType} onChange={(e) => updateForm('orderType', e.target.value as CreateRateCardInput['orderType'])}><option value="B2C">B2C</option><option value="B2B">B2B</option></select></label><label><span className="input-label">From zone</span><select className="input" value={form.fromZoneId} onChange={(e) => updateForm('fromZoneId', e.target.value)} required><option value="">Select</option>{zones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></label><label><span className="input-label">To zone</span><select className="input" value={form.toZoneId} onChange={(e) => updateForm('toZoneId', e.target.value)} required><option value="">Select</option>{zones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></label>{moneyInput('Base price (₹)', 'basePrice')}{moneyInput('Price / kg (₹)', 'pricePerKg')}{moneyInput('COD flat (₹)', 'codSurchargeFlat')}{moneyInput('COD percentage', 'codSurchargePct')}<button className="btn-primary self-end" disabled={busy || !zones.length}>{busy ? 'Saving…' : 'Create rate card'}</button></div></form>
    <section className="mt-8"><div className="flex items-end justify-between"><div><p className="eyebrow">Configuration</p><h2 className="mt-2 font-display text-3xl font-bold">All rate cards</h2></div><button className="text-sm font-bold text-brand-700" onClick={() => void load()} disabled={loading}>Refresh</button></div><div className="panel mt-5 overflow-x-auto p-0"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Type</th><th className="px-5 py-4">Route</th><th className="px-5 py-4">Rate</th><th className="px-5 py-4">Base</th><th className="px-5 py-4">Per kg</th><th className="px-5 py-4">COD</th><th className="px-5 py-4">Status</th><th className="px-5 py-4"></th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan={8} className="px-5 py-10 text-center text-slate-500">Loading rate cards…</td></tr> : cards.length ? cards.map((card) => <tr key={card.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-bold">{card.orderType}</td><td className="px-5 py-4">{card.fromZone.name} → {card.toZone.name}</td><td className="px-5 py-4 capitalize">{card.rateType.replace('_', ' ')}</td><td className="px-5 py-4">₹{card.basePrice.toFixed(2)}</td><td className="px-5 py-4">₹{card.pricePerKg.toFixed(2)}</td><td className="px-5 py-4">₹{card.codSurchargeFlat.toFixed(2)} + {card.codSurchargePct}%</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${card.isActive ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600'}`}>{card.isActive ? 'Active' : 'Inactive'}</span></td><td className="px-5 py-4"><button className="font-bold text-brand-700" onClick={() => setEditing({ ...card })}>Edit</button></td></tr>) : <tr><td colSpan={8} className="px-5 py-10 text-center text-slate-500">No rate cards configured.</td></tr>}</tbody></table></div></section>
    {editing && <div className="fixed inset-0 z-50 grid place-items-center bg-ink/60 p-4" role="dialog" aria-modal="true" aria-label="Edit rate card"><form className="panel w-full max-w-xl" onSubmit={saveEdit}><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Edit rate</p><h2 className="mt-2 font-display text-2xl font-bold">{editing.orderType}: {editing.fromZone.name} → {editing.toZone.name}</h2></div><button type="button" className="text-2xl text-slate-400" onClick={() => setEditing(null)} aria-label="Close">×</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{(['basePrice', 'pricePerKg', 'codSurchargeFlat', 'codSurchargePct'] as const).map((field) => <label key={field}><span className="input-label">{{ basePrice: 'Base price', pricePerKg: 'Price / kg', codSurchargeFlat: 'COD flat', codSurchargePct: 'COD percentage' }[field]}</span><input className="input" type="number" min="0" step="0.01" value={editing[field]} onChange={(e) => setEditing((current) => current ? { ...current, [field]: Number(e.target.value) } : current)} required /></label>)}<label className="flex items-center gap-3 rounded-xl bg-slate-50 p-4 sm:col-span-2"><input type="checkbox" checked={editing.isActive} onChange={(e) => setEditing((current) => current ? { ...current, isActive: e.target.checked } : current)} /><span className="font-semibold">Rate card is active</span></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={() => setEditing(null)}>Cancel</button><button className="btn-primary" disabled={busy}>{busy ? 'Saving…' : 'Save changes'}</button></div></form></div>}
  </div>;
}
