import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getApiErrorMessage } from '../api/client';
import { assignOrder, autoAssignOrder, formatStatus, listAllOrders, listAvailableAgents, ORDER_STATUSES, overrideOrderStatus, type Agent, type Order, type OrderFilters, type OrderStatus, type PaginatedOrders } from '../api/orders.api';
import { listZones, type Zone } from '../api/zones.api';
import { StatusBadge } from '../components/OrderCard';

const emptyResult: PaginatedOrders = { orders: [], pagination: { page: 1, limit: 20, total: 0, totalPages: 0 } };

export default function AdminDashboard() {
  const [result, setResult] = useState(emptyResult); const [zones, setZones] = useState<Zone[]>([]); const [agents, setAgents] = useState<Agent[]>([]); const [assignmentAgents, setAssignmentAgents] = useState<Agent[]>([]); const [filters, setFilters] = useState<OrderFilters>({ page: 1, limit: 20 }); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [assigning, setAssigning] = useState<Order | null>(null); const [agentId, setAgentId] = useState(''); const [overriding, setOverriding] = useState<Order | null>(null); const [overrideStatus, setOverrideStatus] = useState<OrderStatus>('created'); const [overrideNotes, setOverrideNotes] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setResult(await listAllOrders(filters)); } catch (caught) { setError(getApiErrorMessage(caught)); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { Promise.all([listZones(), listAvailableAgents()]).then(([nextZones, nextAgents]) => { setZones(nextZones); setAgents(nextAgents); }).catch((caught) => setError(getApiErrorMessage(caught))); }, []);
  const setFilter = <K extends keyof OrderFilters>(key: K, value: OrderFilters[K]) => setFilters((current) => ({ ...current, [key]: value || undefined, page: key === 'page' ? Number(value) : 1 }));
  async function openAssignment(order: Order) { setAssigning(order); setAgentId(''); setAssignmentAgents([]); setError(''); try { setAssignmentAgents(await listAvailableAgents(order.pickupZoneId)); } catch (caught) { setError(getApiErrorMessage(caught)); } }
  async function manualAssign() { if (!assigning || !agentId) return; setBusy(true); setError(''); try { await assignOrder(assigning.id, agentId); setMessage('Agent assigned successfully.'); setAssigning(null); await load(); } catch (caught) { setError(getApiErrorMessage(caught)); } finally { setBusy(false); } }
  async function autoAssign() { if (!assigning) return; setBusy(true); setError(''); try { const response = await autoAssignOrder(assigning.id); setMessage(response.message ?? 'Automatic assignment completed.'); setAssigning(null); await load(); } catch (caught) { setError(getApiErrorMessage(caught)); } finally { setBusy(false); } }
  function openOverride(order: Order) { setOverriding(order); setOverrideStatus(order.status); setOverrideNotes(''); }
  async function saveOverride() { if (!overriding) return; setBusy(true); setError(''); try { await overrideOrderStatus(overriding.id, overrideStatus, overrideNotes || undefined); setMessage('Order status overridden and logged.'); setOverriding(null); await load(); } catch (caught) { setError(getApiErrorMessage(caught)); } finally { setBusy(false); } }
  const assignable = (status: OrderStatus) => status === 'created' || status === 'rescheduled';
  return <div className="page-shell"><section className="rounded-3xl bg-brand-900 p-6 text-white sm:p-8"><p className="eyebrow text-amber">Control tower</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><div><h1 className="font-display text-4xl font-bold">Delivery operations</h1><p className="mt-2 text-emerald-100">Filter the network, resolve exceptions, and keep assignments moving.</p></div><div className="rounded-2xl bg-white/10 px-6 py-4 text-center"><p className="font-display text-4xl font-bold">{result.pagination.total}</p><p className="text-xs uppercase tracking-wider text-emerald-100">Matching orders</p></div></div></section>
    {(error || message) && <div className={`mt-5 flex items-start justify-between gap-4 rounded-xl p-4 text-sm font-medium ${error ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700'}`}><p>{error || message}</p><button onClick={() => { setError(''); setMessage(''); }} aria-label="Dismiss">×</button></div>}
    <section className="panel mt-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label><span className="input-label">Status</span><select className="input" value={filters.status ?? ''} onChange={(e) => setFilter('status', e.target.value as OrderStatus || undefined)}><option value="">All statuses</option>{ORDER_STATUSES.map((status) => <option key={status} value={status}>{formatStatus(status)}</option>)}</select></label><label><span className="input-label">Zone</span><select className="input" value={filters.zoneId ?? ''} onChange={(e) => setFilter('zoneId', e.target.value || undefined)}><option value="">All zones</option>{zones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></label><label><span className="input-label">Agent</span><select className="input" value={filters.agentId ?? ''} onChange={(e) => setFilter('agentId', e.target.value || undefined)}><option value="">All agents</option>{agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></label><div className="flex items-end"><button className="btn-secondary w-full" onClick={() => setFilters({ page: 1, limit: 20 })}>Clear filters</button></div></div></section>
      <section className="mt-8"><div className="flex items-end justify-between"><div><p className="eyebrow">Network view</p><h2 className="mt-2 font-display text-3xl font-bold">All orders</h2></div><button className="text-sm font-bold text-brand-700" onClick={() => void load()} disabled={loading}>Refresh</button></div><div className="panel mt-5 overflow-x-auto p-0"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Order</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Route</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Agent</th><th className="px-5 py-4">Charge</th><th className="px-5 py-4">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan={7} className="px-5 py-12 text-center text-slate-500">Loading operations…</td></tr> : result.orders.length ? result.orders.map((order) => <tr key={order.id} className="align-top hover:bg-slate-50"><td className="px-5 py-4"><Link to={`/orders/${order.id}`} className="font-bold text-brand-700 hover:underline">#{order.id.slice(0, 8)}</Link><p className="mt-1 text-xs text-slate-400">{new Date(order.createdAt).toLocaleDateString()}</p></td><td className="px-5 py-4"><p className="font-semibold">{order.customer.name}</p><p className="text-xs text-slate-400">{order.customer.email}</p></td><td className="max-w-xs px-5 py-4"><p className="font-semibold">{order.pickupZone.name} → {order.dropZone.name}</p><p className="mt-1 truncate text-xs text-slate-400">{order.pickupAddress}</p></td><td className="px-5 py-4"><StatusBadge status={order.status} /></td><td className="px-5 py-4">{order.assignedAgent?.name ?? <span className="text-slate-400">Unassigned</span>}</td><td className="px-5 py-4 font-bold">₹{order.totalCharge.toFixed(2)}</td><td className="px-5 py-4"><div className="flex gap-2">{assignable(order.status) && <button className="rounded-lg bg-brand-50 px-3 py-2 text-xs font-bold text-brand-700" onClick={() => void openAssignment(order)}>Assign</button>}<button className="rounded-lg bg-amber-100 px-3 py-2 text-xs font-bold text-amber-800" onClick={() => openOverride(order)}>Override</button></div></td></tr>) : <tr><td colSpan={7} className="px-5 py-12 text-center text-slate-500">No orders match these filters.</td></tr>}</tbody></table></div>
      {result.pagination.totalPages > 1 && <div className="mt-5 flex items-center justify-between"><button className="btn-secondary" disabled={result.pagination.page <= 1} onClick={() => setFilter('page', result.pagination.page - 1)}>Previous</button><p className="text-sm text-slate-500">Page {result.pagination.page} of {result.pagination.totalPages}</p><button className="btn-secondary" disabled={result.pagination.page >= result.pagination.totalPages} onClick={() => setFilter('page', result.pagination.page + 1)}>Next</button></div>}</section>
    {assigning && <div className="fixed inset-0 z-50 grid place-items-center bg-ink/60 p-4" role="dialog" aria-modal="true"><div className="panel w-full max-w-lg"><div className="flex justify-between"><div><p className="eyebrow">Assignment</p><h2 className="mt-2 font-display text-2xl font-bold">Order #{assigning.id.slice(0, 8)}</h2><p className="mt-2 text-sm text-slate-500">Eligible pickup zone: {assigning.pickupZone.name}</p></div><button className="text-2xl text-slate-400" onClick={() => setAssigning(null)}>×</button></div><label className="mt-6 block"><span className="input-label">Available agent</span><select className="input" value={agentId} onChange={(e) => setAgentId(e.target.value)}><option value="">Select an agent</option>{assignmentAgents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name} · {agent.activeOrderCount} active</option>)}</select></label>{!assignmentAgents.length && <p className="mt-3 text-sm text-amber-800">No available agents in this pickup zone.</p>}<div className="mt-6 grid gap-3 sm:grid-cols-2"><button className="btn-secondary" onClick={() => void autoAssign()} disabled={busy}>{busy ? 'Assigning…' : 'Auto-assign by load'}</button><button className="btn-primary" onClick={() => void manualAssign()} disabled={busy || !agentId}>{busy ? 'Assigning…' : 'Assign selected'}</button></div></div></div>}
    {overriding && <div className="fixed inset-0 z-50 grid place-items-center bg-ink/60 p-4" role="dialog" aria-modal="true"><div className="panel w-full max-w-lg"><div className="flex justify-between"><div><p className="eyebrow text-amber-700">Admin override</p><h2 className="mt-2 font-display text-2xl font-bold">Change order status</h2><p className="mt-2 text-sm text-slate-500">Every override is written to the order timeline with your identity.</p></div><button className="text-2xl text-slate-400" onClick={() => setOverriding(null)}>×</button></div><label className="mt-6 block"><span className="input-label">New status</span><select className="input" value={overrideStatus} onChange={(e) => setOverrideStatus(e.target.value as OrderStatus)}>{ORDER_STATUSES.map((status) => <option key={status} value={status}>{formatStatus(status)}</option>)}</select></label><label className="mt-4 block"><span className="input-label">Override notes</span><textarea className="input min-h-24" value={overrideNotes} onChange={(e) => setOverrideNotes(e.target.value)} placeholder="Explain why this override is needed" /></label><button className="btn-primary mt-6 w-full bg-amber-600 hover:bg-amber-700" onClick={() => void saveOverride()} disabled={busy}>{busy ? 'Saving override…' : 'Confirm override'}</button></div></div>}
  </div>;
}
