import { useCallback, useEffect, useState } from 'react';
import { getApiErrorMessage } from '../api/client';
import { ALLOWED_TRANSITIONS, formatStatus, listAssignedOrders, updateOrderStatus, type Order, type OrderStatus } from '../api/orders.api';
import { OrderCard } from '../components/OrderCard';
import { useAuth } from '../context/AuthContext';

interface UpdateDraft { status: OrderStatus; notes: string }

export default function AgentDashboard() {
  const { user } = useAuth(); const [orders, setOrders] = useState<Order[]>([]); const [drafts, setDrafts] = useState<Record<string, UpdateDraft>>({}); const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setOrders(await listAssignedOrders()); } catch (caught) { setError(getApiErrorMessage(caught)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const draftFor = (order: Order): UpdateDraft => drafts[order.id] ?? { status: ALLOWED_TRANSITIONS[order.status][0], notes: '' };
  async function update(order: Order) { const draft = draftFor(order); if (!draft.status) return; setBusyId(order.id); setError(''); setMessage(''); try { await updateOrderStatus(order.id, draft.status, draft.notes || undefined); setMessage(`Order #${order.id.slice(0, 8)} moved to ${formatStatus(draft.status)}.`); setDrafts((current) => { const next = { ...current }; delete next[order.id]; return next; }); await load(); } catch (caught) { setError(getApiErrorMessage(caught)); } finally { setBusyId(''); } }
  const active = orders.filter((order) => ALLOWED_TRANSITIONS[order.status].length > 0).length;

  return <div className="page-shell"><section className="rounded-3xl bg-ink p-6 text-white sm:p-8"><p className="eyebrow text-amber">Agent workspace</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-display text-4xl font-bold">Your delivery run</h1><p className="mt-2 text-slate-300">Welcome, {user?.name}. Update each handoff as it happens.</p></div><div className="rounded-2xl bg-white/10 px-5 py-3 text-center"><p className="text-3xl font-bold">{active}</p><p className="text-xs uppercase tracking-wider text-slate-300">Active stops</p></div></div></section>
    {(error || message) && <p role="status" className={`mt-5 rounded-xl p-4 text-sm font-medium ${error ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700'}`}>{error || message}</p>}
    <div className="mt-8 flex items-center justify-between"><div><p className="eyebrow">Assignments</p><h2 className="mt-2 font-display text-3xl font-bold">Assigned orders</h2></div><button className="text-sm font-bold text-brand-700" onClick={() => void load()} disabled={loading}>Refresh</button></div>
    {loading ? <div className="panel mt-5 animate-pulse text-slate-500">Loading assigned deliveries…</div> : orders.length ? <div className="mt-5 grid gap-5 lg:grid-cols-2">{orders.map((order) => { const next = ALLOWED_TRANSITIONS[order.status]; const draft = draftFor(order); return <OrderCard key={order.id} order={order} footer={next.length ? <div className="space-y-3"><label><span className="input-label">Next status</span><select className="input" value={draft.status} onChange={(e) => setDrafts((current) => ({ ...current, [order.id]: { ...draft, status: e.target.value as OrderStatus } }))}>{next.map((status) => <option key={status} value={status}>{formatStatus(status)}</option>)}</select></label><label><span className="input-label">Update notes {draft.status === 'failed' ? '(failure reason)' : '(optional)'}</span><input className="input" value={draft.notes} onChange={(e) => setDrafts((current) => ({ ...current, [order.id]: { ...draft, notes: e.target.value } }))} required={draft.status === 'failed'} placeholder={draft.status === 'failed' ? 'Why could delivery not be completed?' : 'Add a handoff note'} /></label><button className="btn-primary w-full" onClick={() => void update(order)} disabled={busyId === order.id || (draft.status === 'failed' && !draft.notes.trim())}>{busyId === order.id ? 'Updating…' : `Mark ${formatStatus(draft.status)}`}</button></div> : <p className="text-sm font-semibold text-slate-500">This delivery has no further agent actions.</p>} />; })}</div> : <div className="panel mt-5 py-12 text-center"><p className="font-display text-2xl font-bold">No assignments</p><p className="mt-2 text-slate-500">New deliveries assigned to you will appear here.</p></div>}
  </div>;
}
